server:
  port: 8899

spring:
  profiles:
    active: dev
  application:
    name: micro-auth
  datasource:
    url:  jdbc:mysql://localhost:3306/record?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/

#security:
#  oauth2:
#    resource:
#      filter-order: 3

mybatis:
  configuration:
    map-underscore-to-camel-case: true